### ISSUE TITLE
Nice - Firefox Problem

### ISSUE THREAD

**Issue by tyeeman** [girobusan/imp#2]
Very Nice. I'm using Firefox latest version and I'm getting overlap of the top buttons onto the markdown menu like this - 

<img width="369" alt="2022-12-01_225520" src="https://user-images.githubusercontent.com/4469306/205233897-47b925f6-ee00-46d9-88db-e58e3b7dc2fc.png">

Also, images written in markdown are not showing up?

**Comment by tyeeman** [comment]
I added my own css and everything looks good except images fall outside the main width. Text wraps nicely but images are not sized by the browser. Is there a way to do this in markdown or does the markdown to html converter have to do it?

Update - used this to auto resize images. Supposedly works on all platforms too!
```
<style>
img {
    padding: 0;
    display: block;
    margin: 0 auto;
    max-height: 100%;
    max-width: 90%;
}
</style>
```

**Comment by tyeeman** [comment]
I'm trying to make a horizontal rule line. Nothing works. ---, ___, ***. 

Please give it a try.

**Comment by girobusan** [comment]
Thank you for reporting! 
Horizontal rule (for current version) made from --- (three minuses). You'll need to add empty string above and below it.
Also I've improved preview, now it s shows almost everything as is.

Buttons will be moved to the toolbar, give me couple of days. Now there is no need to keep them as separate widget.

**Comment by tyeeman** [comment]
Thanks for the info! I see when the page is saved to html it includes the markdown also. It doesn't show, but this can double the size of the file. Is it easy to remove the markdown text when saving the  html?

**Comment by girobusan** [comment]
Markdown source saved within resulting html for future editing. If you remove markdown part, you'll not be able to edit your file as markdown. Or you'd keep two versions of your file, one editable, and other —  not...  I think, the overhead is rather small and almost unsignificant — it's just text.
